# Generated by Django 2.1.2 on 2018-10-04 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Acto académico',
                'db_table': 'sg_acto_academico',
                'default_permissions': (),
                'verbose_name': 'Acto académico',
                'permissions': (('add_actoacademico', 'Puede agregar ActoAcademico'), ('change_actoacademico', 'Puede actualizar ActoAcademico'), ('delete_actoacademico', 'Puede eliminar ActoAcademico'), ('list_actoacademico', 'Puede listar ActoAcademico'), ('get_actoacademico', 'Puede obtener ActoAcademico')),
            },
        ),
    ]
